name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install node packages
        run: npm ci --legacy-peer-deps
        
      - name: Check lint
        run: npm run check:lint
        
      - name: Check prettier
        run: npm run check:prettier
      
      - name: Build
        run: npm run build
